#debug: true
server:
  port: 8080
  error:
    include-message: ALWAYS
#    servlet:
#        context-path: /api
spring:
#  cloud:
#    aws:
#      s3:
#        region: us-east-1
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  flyway:
    baselineOnMigrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    open-in-view: false
  #            hibernate:
  #                dialect: org.hibernate.dialect.MySQLDialect spring.jpa.open-in-view=false

  #    spring.jpa.hibernate.ddl-auto=update
  datasource:
    url: jdbc:postgresql://localhost:5432/photo_db
    username: photo_db
    password: photo_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true


