server:
  port: 8000
#    servlet:
#        context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    open-in-view: false
  #            hibernate:
  #                dialect: org.hibernate.dialect.MySQLDialect spring.jpa.open-in-view=false

  #    spring.jpa.hibernate.ddl-auto=update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/macjig_test
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true


